class Solution:
    def intToRoman(self, num: int) -> str:
        string=''
        while(num!=0):
            if(num>=1000):
                n=num//1000
                string=string+'M'*n
                num=num-(1000*n)
            elif(num>=500):
                n=num//500
                if(num//100==9):
                    string=string+'CM'
                    num=num-900
                else:
                    string=string+'D'*n
                    num=num-(500*n)
            elif(num>=100):
                n=num//100
                if(num//100==4):
                    string=string+'CD'
                    num=num-400
                else:
                    string=string+'C'*n
                    num=num-(100*n)
            elif(num>=50):
                n=num//50
                if(num//10==9):
                    string=string+'XC'
                    num=num-90
                else:
                    string=string+'L'*n
                    num=num-(50*n)
            elif(num>=10):
                n=num//10
                if(num//10==4):
                    string=string+'XL'
                    num=num-40
                else:
                    string=string+'X'*n
                    num=num-(10*n)
            elif(num>=5):
                n=num//5
                if(num//1==9):
                    string=string+'IX'
                    num=num-9
                else:
                    string=string+'V'*n
                    num=num-(5*n)
            elif(num>=1):
                n=num//1
                if(num//1==4):
                    string=string+'IV'
                    num=num-4
                else:
                    string=string+'I'*n
                    num=num-(1*n)
        return string
            